// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBlogListResponse.proto

package com.luckey.request_respose;

public final class GetBlogListResponse {
  private GetBlogListResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBlogListResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBlogListResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.luckey.request_respose.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.luckey.request_respose.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>optional bool isLastPage = 2;</code>
     */
    boolean getIsLastPage();

    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    java.util.List<BlogMessage>
        getBlogsList();
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    com.luckey.request_respose.GetBlogListResponse.BlogMessage getBlogs(int index);
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    int getBlogsCount();
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    java.util.List<? extends BlogMessageOrBuilder>
        getBlogsOrBuilderList();
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    com.luckey.request_respose.GetBlogListResponse.BlogMessageOrBuilder getBlogsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetBlogListResponseMessage}
   */
  public  static final class GetBlogListResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBlogListResponseMessage)
      GetBlogListResponseMessageOrBuilder {
    // Use GetBlogListResponseMessage.newBuilder() to construct.
    private GetBlogListResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBlogListResponseMessage() {
      isLastPage_ = false;
      blogs_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBlogListResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.luckey.request_respose.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.luckey.request_respose.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              isLastPage_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                blogs_ = new java.util.ArrayList<BlogMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              blogs_.add(
                  input.readMessage(com.luckey.request_respose.GetBlogListResponse.BlogMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          blogs_ = java.util.Collections.unmodifiableList(blogs_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luckey.request_respose.GetBlogListResponse.internal_static_GetBlogListResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luckey.request_respose.GetBlogListResponse.internal_static_GetBlogListResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage.class, com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.luckey.request_respose.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.luckey.request_respose.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.luckey.request_respose.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.luckey.request_respose.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int ISLASTPAGE_FIELD_NUMBER = 2;
    private boolean isLastPage_;
    /**
     * <code>optional bool isLastPage = 2;</code>
     */
    public boolean getIsLastPage() {
      return isLastPage_;
    }

    public static final int BLOGS_FIELD_NUMBER = 3;
    private java.util.List<BlogMessage> blogs_;
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    public java.util.List<BlogMessage> getBlogsList() {
      return blogs_;
    }
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    public java.util.List<? extends BlogMessageOrBuilder>
        getBlogsOrBuilderList() {
      return blogs_;
    }
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    public int getBlogsCount() {
      return blogs_.size();
    }
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    public com.luckey.request_respose.GetBlogListResponse.BlogMessage getBlogs(int index) {
      return blogs_.get(index);
    }
    /**
     * <code>repeated .BlogMessage blogs = 3;</code>
     */
    public com.luckey.request_respose.GetBlogListResponse.BlogMessageOrBuilder getBlogsOrBuilder(
        int index) {
      return blogs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      if (isLastPage_ != false) {
        output.writeBool(2, isLastPage_);
      }
      for (int i = 0; i < blogs_.size(); i++) {
        output.writeMessage(3, blogs_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      if (isLastPage_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isLastPage_);
      }
      for (int i = 0; i < blogs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, blogs_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage)) {
        return super.equals(obj);
      }
      com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage other = (com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && (getIsLastPage()
          == other.getIsLastPage());
      result = result && getBlogsList()
          .equals(other.getBlogsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      hash = (37 * hash) + ISLASTPAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLastPage());
      if (getBlogsCount() > 0) {
        hash = (37 * hash) + BLOGS_FIELD_NUMBER;
        hash = (53 * hash) + getBlogsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBlogListResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBlogListResponseMessage)
        com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luckey.request_respose.GetBlogListResponse.internal_static_GetBlogListResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luckey.request_respose.GetBlogListResponse.internal_static_GetBlogListResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage.class, com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage.Builder.class);
      }

      // Construct using com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBlogsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        isLastPage_ = false;

        if (blogsBuilder_ == null) {
          blogs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          blogsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luckey.request_respose.GetBlogListResponse.internal_static_GetBlogListResponseMessage_descriptor;
      }

      public com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage getDefaultInstanceForType() {
        return com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage.getDefaultInstance();
      }

      public com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage build() {
        com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage buildPartial() {
        com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage result = new com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        result.isLastPage_ = isLastPage_;
        if (blogsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            blogs_ = java.util.Collections.unmodifiableList(blogs_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.blogs_ = blogs_;
        } else {
          result.blogs_ = blogsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage) {
          return mergeFrom((com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage other) {
        if (other == com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (other.getIsLastPage() != false) {
          setIsLastPage(other.getIsLastPage());
        }
        if (blogsBuilder_ == null) {
          if (!other.blogs_.isEmpty()) {
            if (blogs_.isEmpty()) {
              blogs_ = other.blogs_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBlogsIsMutable();
              blogs_.addAll(other.blogs_);
            }
            onChanged();
          }
        } else {
          if (!other.blogs_.isEmpty()) {
            if (blogsBuilder_.isEmpty()) {
              blogsBuilder_.dispose();
              blogsBuilder_ = null;
              blogs_ = other.blogs_;
              bitField0_ = (bitField0_ & ~0x00000004);
              blogsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBlogsFieldBuilder() : null;
            } else {
              blogsBuilder_.addAllMessages(other.blogs_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.luckey.request_respose.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.luckey.request_respose.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.luckey.request_respose.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.luckey.request_respose.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.luckey.request_respose.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.luckey.request_respose.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.luckey.request_respose.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.luckey.request_respose.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {

        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.luckey.request_respose.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.luckey.request_respose.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private boolean isLastPage_ ;
      /**
       * <code>optional bool isLastPage = 2;</code>
       */
      public boolean getIsLastPage() {
        return isLastPage_;
      }
      /**
       * <code>optional bool isLastPage = 2;</code>
       */
      public Builder setIsLastPage(boolean value) {

        isLastPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isLastPage = 2;</code>
       */
      public Builder clearIsLastPage() {

        isLastPage_ = false;
        onChanged();
        return this;
      }

      private java.util.List<BlogMessage> blogs_ =
        java.util.Collections.emptyList();
      private void ensureBlogsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          blogs_ = new java.util.ArrayList<BlogMessage>(blogs_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          BlogMessage, BlogMessage.Builder, BlogMessageOrBuilder> blogsBuilder_;

      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public java.util.List<BlogMessage> getBlogsList() {
        if (blogsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(blogs_);
        } else {
          return blogsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public int getBlogsCount() {
        if (blogsBuilder_ == null) {
          return blogs_.size();
        } else {
          return blogsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public com.luckey.request_respose.GetBlogListResponse.BlogMessage getBlogs(int index) {
        if (blogsBuilder_ == null) {
          return blogs_.get(index);
        } else {
          return blogsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder setBlogs(
          int index, com.luckey.request_respose.GetBlogListResponse.BlogMessage value) {
        if (blogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlogsIsMutable();
          blogs_.set(index, value);
          onChanged();
        } else {
          blogsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder setBlogs(
          int index, com.luckey.request_respose.GetBlogListResponse.BlogMessage.Builder builderForValue) {
        if (blogsBuilder_ == null) {
          ensureBlogsIsMutable();
          blogs_.set(index, builderForValue.build());
          onChanged();
        } else {
          blogsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder addBlogs(com.luckey.request_respose.GetBlogListResponse.BlogMessage value) {
        if (blogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlogsIsMutable();
          blogs_.add(value);
          onChanged();
        } else {
          blogsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder addBlogs(
          int index, com.luckey.request_respose.GetBlogListResponse.BlogMessage value) {
        if (blogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlogsIsMutable();
          blogs_.add(index, value);
          onChanged();
        } else {
          blogsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder addBlogs(
          com.luckey.request_respose.GetBlogListResponse.BlogMessage.Builder builderForValue) {
        if (blogsBuilder_ == null) {
          ensureBlogsIsMutable();
          blogs_.add(builderForValue.build());
          onChanged();
        } else {
          blogsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder addBlogs(
          int index, com.luckey.request_respose.GetBlogListResponse.BlogMessage.Builder builderForValue) {
        if (blogsBuilder_ == null) {
          ensureBlogsIsMutable();
          blogs_.add(index, builderForValue.build());
          onChanged();
        } else {
          blogsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder addAllBlogs(
          Iterable<? extends BlogMessage> values) {
        if (blogsBuilder_ == null) {
          ensureBlogsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, blogs_);
          onChanged();
        } else {
          blogsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder clearBlogs() {
        if (blogsBuilder_ == null) {
          blogs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          blogsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public Builder removeBlogs(int index) {
        if (blogsBuilder_ == null) {
          ensureBlogsIsMutable();
          blogs_.remove(index);
          onChanged();
        } else {
          blogsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public com.luckey.request_respose.GetBlogListResponse.BlogMessage.Builder getBlogsBuilder(
          int index) {
        return getBlogsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public com.luckey.request_respose.GetBlogListResponse.BlogMessageOrBuilder getBlogsOrBuilder(
          int index) {
        if (blogsBuilder_ == null) {
          return blogs_.get(index);  } else {
          return blogsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public java.util.List<? extends BlogMessageOrBuilder>
           getBlogsOrBuilderList() {
        if (blogsBuilder_ != null) {
          return blogsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(blogs_);
        }
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public com.luckey.request_respose.GetBlogListResponse.BlogMessage.Builder addBlogsBuilder() {
        return getBlogsFieldBuilder().addBuilder(
            com.luckey.request_respose.GetBlogListResponse.BlogMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public com.luckey.request_respose.GetBlogListResponse.BlogMessage.Builder addBlogsBuilder(
          int index) {
        return getBlogsFieldBuilder().addBuilder(
            index, com.luckey.request_respose.GetBlogListResponse.BlogMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .BlogMessage blogs = 3;</code>
       */
      public java.util.List<BlogMessage.Builder>
           getBlogsBuilderList() {
        return getBlogsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          BlogMessage, BlogMessage.Builder, BlogMessageOrBuilder>
          getBlogsFieldBuilder() {
        if (blogsBuilder_ == null) {
          blogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              BlogMessage, BlogMessage.Builder, BlogMessageOrBuilder>(
                  blogs_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          blogs_ = null;
        }
        return blogsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetBlogListResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetBlogListResponseMessage)
    private static final com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage();
    }

    public static com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBlogListResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetBlogListResponseMessage>() {
      public GetBlogListResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBlogListResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBlogListResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetBlogListResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.luckey.request_respose.GetBlogListResponse.GetBlogListResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BlogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 blogId = 1;</code>
     */
    long getBlogId();

    /**
     * <code>optional string content = 2;</code>
     */
    String getContent();
    /**
     * <code>optional string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional double longitude = 3;</code>
     */
    double getLongitude();

    /**
     * <code>optional double latitude = 4;</code>
     */
    double getLatitude();

    /**
     * <code>optional string address = 5;</code>
     */
    String getAddress();
    /**
     * <code>optional string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional int32 likeCount = 6;</code>
     */
    int getLikeCount();

    /**
     * <code>optional int32 commentCount = 7;</code>
     */
    int getCommentCount();

    /**
     * <code>optional int64 userId = 8;</code>
     */
    long getUserId();

    /**
     * <code>optional bool isLike = 9;</code>
     */
    boolean getIsLike();

    /**
     * <code>optional string author = 10;</code>
     */
    String getAuthor();
    /**
     * <code>optional string author = 10;</code>
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>optional string authorPhoto = 11;</code>
     */
    String getAuthorPhoto();
    /**
     * <code>optional string authorPhoto = 11;</code>
     */
    com.google.protobuf.ByteString
        getAuthorPhotoBytes();

    /**
     * <code>optional int64 createDt = 12;</code>
     */
    long getCreateDt();

    /**
     * <code>repeated string images = 13;</code>
     */
    java.util.List<String>
        getImagesList();
    /**
     * <code>repeated string images = 13;</code>
     */
    int getImagesCount();
    /**
     * <code>repeated string images = 13;</code>
     */
    String getImages(int index);
    /**
     * <code>repeated string images = 13;</code>
     */
    com.google.protobuf.ByteString
        getImagesBytes(int index);
  }
  /**
   * Protobuf type {@code BlogMessage}
   */
  public  static final class BlogMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BlogMessage)
      BlogMessageOrBuilder {
    // Use BlogMessage.newBuilder() to construct.
    private BlogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlogMessage() {
      blogId_ = 0L;
      content_ = "";
      longitude_ = 0D;
      latitude_ = 0D;
      address_ = "";
      likeCount_ = 0;
      commentCount_ = 0;
      userId_ = 0L;
      isLike_ = false;
      author_ = "";
      authorPhoto_ = "";
      createDt_ = 0L;
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BlogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              blogId_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 25: {

              longitude_ = input.readDouble();
              break;
            }
            case 33: {

              latitude_ = input.readDouble();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 48: {

              likeCount_ = input.readInt32();
              break;
            }
            case 56: {

              commentCount_ = input.readInt32();
              break;
            }
            case 64: {

              userId_ = input.readInt64();
              break;
            }
            case 72: {

              isLike_ = input.readBool();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              author_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              authorPhoto_ = s;
              break;
            }
            case 96: {

              createDt_ = input.readInt64();
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
                images_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00001000;
              }
              images_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
          images_ = images_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luckey.request_respose.GetBlogListResponse.internal_static_BlogMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luckey.request_respose.GetBlogListResponse.internal_static_BlogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luckey.request_respose.GetBlogListResponse.BlogMessage.class, com.luckey.request_respose.GetBlogListResponse.BlogMessage.Builder.class);
    }

    private int bitField0_;
    public static final int BLOGID_FIELD_NUMBER = 1;
    private long blogId_;
    /**
     * <code>optional int64 blogId = 1;</code>
     */
    public long getBlogId() {
      return blogId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile Object content_;
    /**
     * <code>optional string content = 2;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>optional string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private double longitude_;
    /**
     * <code>optional double longitude = 3;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 4;
    private double latitude_;
    /**
     * <code>optional double latitude = 4;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile Object address_;
    /**
     * <code>optional string address = 5;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIKECOUNT_FIELD_NUMBER = 6;
    private int likeCount_;
    /**
     * <code>optional int32 likeCount = 6;</code>
     */
    public int getLikeCount() {
      return likeCount_;
    }

    public static final int COMMENTCOUNT_FIELD_NUMBER = 7;
    private int commentCount_;
    /**
     * <code>optional int32 commentCount = 7;</code>
     */
    public int getCommentCount() {
      return commentCount_;
    }

    public static final int USERID_FIELD_NUMBER = 8;
    private long userId_;
    /**
     * <code>optional int64 userId = 8;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int ISLIKE_FIELD_NUMBER = 9;
    private boolean isLike_;
    /**
     * <code>optional bool isLike = 9;</code>
     */
    public boolean getIsLike() {
      return isLike_;
    }

    public static final int AUTHOR_FIELD_NUMBER = 10;
    private volatile Object author_;
    /**
     * <code>optional string author = 10;</code>
     */
    public String getAuthor() {
      Object ref = author_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <code>optional string author = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORPHOTO_FIELD_NUMBER = 11;
    private volatile Object authorPhoto_;
    /**
     * <code>optional string authorPhoto = 11;</code>
     */
    public String getAuthorPhoto() {
      Object ref = authorPhoto_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        authorPhoto_ = s;
        return s;
      }
    }
    /**
     * <code>optional string authorPhoto = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorPhotoBytes() {
      Object ref = authorPhoto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        authorPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDT_FIELD_NUMBER = 12;
    private long createDt_;
    /**
     * <code>optional int64 createDt = 12;</code>
     */
    public long getCreateDt() {
      return createDt_;
    }

    public static final int IMAGES_FIELD_NUMBER = 13;
    private com.google.protobuf.LazyStringList images_;
    /**
     * <code>repeated string images = 13;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getImagesList() {
      return images_;
    }
    /**
     * <code>repeated string images = 13;</code>
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated string images = 13;</code>
     */
    public String getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated string images = 13;</code>
     */
    public com.google.protobuf.ByteString
        getImagesBytes(int index) {
      return images_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blogId_ != 0L) {
        output.writeInt64(1, blogId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(3, longitude_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(4, latitude_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      if (likeCount_ != 0) {
        output.writeInt32(6, likeCount_);
      }
      if (commentCount_ != 0) {
        output.writeInt32(7, commentCount_);
      }
      if (userId_ != 0L) {
        output.writeInt64(8, userId_);
      }
      if (isLike_ != false) {
        output.writeBool(9, isLike_);
      }
      if (!getAuthorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, author_);
      }
      if (!getAuthorPhotoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, authorPhoto_);
      }
      if (createDt_ != 0L) {
        output.writeInt64(12, createDt_);
      }
      for (int i = 0; i < images_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, images_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blogId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, blogId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, longitude_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, latitude_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      if (likeCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, likeCount_);
      }
      if (commentCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, commentCount_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, userId_);
      }
      if (isLike_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, isLike_);
      }
      if (!getAuthorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, author_);
      }
      if (!getAuthorPhotoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, authorPhoto_);
      }
      if (createDt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, createDt_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < images_.size(); i++) {
          dataSize += computeStringSizeNoTag(images_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getImagesList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.luckey.request_respose.GetBlogListResponse.BlogMessage)) {
        return super.equals(obj);
      }
      com.luckey.request_respose.GetBlogListResponse.BlogMessage other = (com.luckey.request_respose.GetBlogListResponse.BlogMessage) obj;

      boolean result = true;
      result = result && (getBlogId()
          == other.getBlogId());
      result = result && getContent()
          .equals(other.getContent());
      result = result && (
          Double.doubleToLongBits(getLongitude())
          == Double.doubleToLongBits(
              other.getLongitude()));
      result = result && (
          Double.doubleToLongBits(getLatitude())
          == Double.doubleToLongBits(
              other.getLatitude()));
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && (getLikeCount()
          == other.getLikeCount());
      result = result && (getCommentCount()
          == other.getCommentCount());
      result = result && (getUserId()
          == other.getUserId());
      result = result && (getIsLike()
          == other.getIsLike());
      result = result && getAuthor()
          .equals(other.getAuthor());
      result = result && getAuthorPhoto()
          .equals(other.getAuthorPhoto());
      result = result && (getCreateDt()
          == other.getCreateDt());
      result = result && getImagesList()
          .equals(other.getImagesList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BLOGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlogId());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + LIKECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getLikeCount();
      hash = (37 * hash) + COMMENTCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCommentCount();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + ISLIKE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLike());
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      hash = (37 * hash) + AUTHORPHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorPhoto().hashCode();
      hash = (37 * hash) + CREATEDT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateDt());
      if (getImagesCount() > 0) {
        hash = (37 * hash) + IMAGES_FIELD_NUMBER;
        hash = (53 * hash) + getImagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.luckey.request_respose.GetBlogListResponse.BlogMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BlogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BlogMessage)
        com.luckey.request_respose.GetBlogListResponse.BlogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luckey.request_respose.GetBlogListResponse.internal_static_BlogMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luckey.request_respose.GetBlogListResponse.internal_static_BlogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luckey.request_respose.GetBlogListResponse.BlogMessage.class, com.luckey.request_respose.GetBlogListResponse.BlogMessage.Builder.class);
      }

      // Construct using com.luckey.request_respose.GetBlogListResponse.BlogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        blogId_ = 0L;

        content_ = "";

        longitude_ = 0D;

        latitude_ = 0D;

        address_ = "";

        likeCount_ = 0;

        commentCount_ = 0;

        userId_ = 0L;

        isLike_ = false;

        author_ = "";

        authorPhoto_ = "";

        createDt_ = 0L;

        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luckey.request_respose.GetBlogListResponse.internal_static_BlogMessage_descriptor;
      }

      public com.luckey.request_respose.GetBlogListResponse.BlogMessage getDefaultInstanceForType() {
        return com.luckey.request_respose.GetBlogListResponse.BlogMessage.getDefaultInstance();
      }

      public com.luckey.request_respose.GetBlogListResponse.BlogMessage build() {
        com.luckey.request_respose.GetBlogListResponse.BlogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luckey.request_respose.GetBlogListResponse.BlogMessage buildPartial() {
        com.luckey.request_respose.GetBlogListResponse.BlogMessage result = new com.luckey.request_respose.GetBlogListResponse.BlogMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.blogId_ = blogId_;
        result.content_ = content_;
        result.longitude_ = longitude_;
        result.latitude_ = latitude_;
        result.address_ = address_;
        result.likeCount_ = likeCount_;
        result.commentCount_ = commentCount_;
        result.userId_ = userId_;
        result.isLike_ = isLike_;
        result.author_ = author_;
        result.authorPhoto_ = authorPhoto_;
        result.createDt_ = createDt_;
        if (((bitField0_ & 0x00001000) == 0x00001000)) {
          images_ = images_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00001000);
        }
        result.images_ = images_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luckey.request_respose.GetBlogListResponse.BlogMessage) {
          return mergeFrom((com.luckey.request_respose.GetBlogListResponse.BlogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luckey.request_respose.GetBlogListResponse.BlogMessage other) {
        if (other == com.luckey.request_respose.GetBlogListResponse.BlogMessage.getDefaultInstance()) return this;
        if (other.getBlogId() != 0L) {
          setBlogId(other.getBlogId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getLikeCount() != 0) {
          setLikeCount(other.getLikeCount());
        }
        if (other.getCommentCount() != 0) {
          setCommentCount(other.getCommentCount());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getIsLike() != false) {
          setIsLike(other.getIsLike());
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          onChanged();
        }
        if (!other.getAuthorPhoto().isEmpty()) {
          authorPhoto_ = other.authorPhoto_;
          onChanged();
        }
        if (other.getCreateDt() != 0L) {
          setCreateDt(other.getCreateDt());
        }
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00001000);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luckey.request_respose.GetBlogListResponse.BlogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luckey.request_respose.GetBlogListResponse.BlogMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long blogId_ ;
      /**
       * <code>optional int64 blogId = 1;</code>
       */
      public long getBlogId() {
        return blogId_;
      }
      /**
       * <code>optional int64 blogId = 1;</code>
       */
      public Builder setBlogId(long value) {

        blogId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 blogId = 1;</code>
       */
      public Builder clearBlogId() {

        blogId_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>optional string content = 2;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>optional double longitude = 3;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional double longitude = 3;</code>
       */
      public Builder setLongitude(double value) {

        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double longitude = 3;</code>
       */
      public Builder clearLongitude() {

        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>optional double latitude = 4;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional double latitude = 4;</code>
       */
      public Builder setLatitude(double value) {

        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latitude = 4;</code>
       */
      public Builder clearLatitude() {

        latitude_ = 0D;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>optional string address = 5;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        address_ = value;
        onChanged();
        return this;
      }

      private int likeCount_ ;
      /**
       * <code>optional int32 likeCount = 6;</code>
       */
      public int getLikeCount() {
        return likeCount_;
      }
      /**
       * <code>optional int32 likeCount = 6;</code>
       */
      public Builder setLikeCount(int value) {

        likeCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 likeCount = 6;</code>
       */
      public Builder clearLikeCount() {

        likeCount_ = 0;
        onChanged();
        return this;
      }

      private int commentCount_ ;
      /**
       * <code>optional int32 commentCount = 7;</code>
       */
      public int getCommentCount() {
        return commentCount_;
      }
      /**
       * <code>optional int32 commentCount = 7;</code>
       */
      public Builder setCommentCount(int value) {

        commentCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 commentCount = 7;</code>
       */
      public Builder clearCommentCount() {

        commentCount_ = 0;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>optional int64 userId = 8;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 8;</code>
       */
      public Builder setUserId(long value) {

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 8;</code>
       */
      public Builder clearUserId() {

        userId_ = 0L;
        onChanged();
        return this;
      }

      private boolean isLike_ ;
      /**
       * <code>optional bool isLike = 9;</code>
       */
      public boolean getIsLike() {
        return isLike_;
      }
      /**
       * <code>optional bool isLike = 9;</code>
       */
      public Builder setIsLike(boolean value) {

        isLike_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isLike = 9;</code>
       */
      public Builder clearIsLike() {

        isLike_ = false;
        onChanged();
        return this;
      }

      private Object author_ = "";
      /**
       * <code>optional string author = 10;</code>
       */
      public String getAuthor() {
        Object ref = author_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder setAuthor(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder clearAuthor() {

        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        author_ = value;
        onChanged();
        return this;
      }

      private Object authorPhoto_ = "";
      /**
       * <code>optional string authorPhoto = 11;</code>
       */
      public String getAuthorPhoto() {
        Object ref = authorPhoto_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          authorPhoto_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string authorPhoto = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorPhotoBytes() {
        Object ref = authorPhoto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          authorPhoto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string authorPhoto = 11;</code>
       */
      public Builder setAuthorPhoto(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        authorPhoto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string authorPhoto = 11;</code>
       */
      public Builder clearAuthorPhoto() {

        authorPhoto_ = getDefaultInstance().getAuthorPhoto();
        onChanged();
        return this;
      }
      /**
       * <code>optional string authorPhoto = 11;</code>
       */
      public Builder setAuthorPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        authorPhoto_ = value;
        onChanged();
        return this;
      }

      private long createDt_ ;
      /**
       * <code>optional int64 createDt = 12;</code>
       */
      public long getCreateDt() {
        return createDt_;
      }
      /**
       * <code>optional int64 createDt = 12;</code>
       */
      public Builder setCreateDt(long value) {

        createDt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createDt = 12;</code>
       */
      public Builder clearCreateDt() {

        createDt_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00001000) == 0x00001000)) {
          images_ = new com.google.protobuf.LazyStringArrayList(images_);
          bitField0_ |= 0x00001000;
         }
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getImagesList() {
        return images_.getUnmodifiableView();
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public int getImagesCount() {
        return images_.size();
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public String getImages(int index) {
        return images_.get(index);
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public com.google.protobuf.ByteString
          getImagesBytes(int index) {
        return images_.getByteString(index);
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public Builder setImages(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public Builder addImages(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public Builder addAllImages(
          Iterable<String> values) {
        ensureImagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, images_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public Builder clearImages() {
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 13;</code>
       */
      public Builder addImagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BlogMessage)
    }

    // @@protoc_insertion_point(class_scope:BlogMessage)
    private static final com.luckey.request_respose.GetBlogListResponse.BlogMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.luckey.request_respose.GetBlogListResponse.BlogMessage();
    }

    public static com.luckey.request_respose.GetBlogListResponse.BlogMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlogMessage>
        PARSER = new com.google.protobuf.AbstractParser<BlogMessage>() {
      public BlogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlogMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlogMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BlogMessage> getParserForType() {
      return PARSER;
    }

    public com.luckey.request_respose.GetBlogListResponse.BlogMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBlogListResponseMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBlogListResponseMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlogMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031GetBlogListResponse.proto\032\032ErrorMessag" +
      "eResponse.proto\"n\n\032GetBlogListResponseMe" +
      "ssage\022\037\n\010errorMsg\030\001 \001(\0132\r.ErrorMessage\022\022" +
      "\n\nisLastPage\030\002 \001(\010\022\033\n\005blogs\030\003 \003(\0132\014.Blog" +
      "Message\"\364\001\n\013BlogMessage\022\016\n\006blogId\030\001 \001(\003\022" +
      "\017\n\007content\030\002 \001(\t\022\021\n\tlongitude\030\003 \001(\001\022\020\n\010l" +
      "atitude\030\004 \001(\001\022\017\n\007address\030\005 \001(\t\022\021\n\tlikeCo" +
      "unt\030\006 \001(\005\022\024\n\014commentCount\030\007 \001(\005\022\016\n\006userI" +
      "d\030\010 \001(\003\022\016\n\006isLike\030\t \001(\010\022\016\n\006author\030\n \001(\t\022" +
      "\023\n\013authorPhoto\030\013 \001(\t\022\020\n\010createDt\030\014 \001(\003\022\016",
      "\n\006images\030\r \003(\tB/\n\030com.cq.esmoking.respon" +
      "seB\023GetBlogListResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.luckey.request_respose.ErrorMessageResponse.getDescriptor(),
        }, assigner);
    internal_static_GetBlogListResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBlogListResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBlogListResponseMessage_descriptor,
        new String[] { "ErrorMsg", "IsLastPage", "Blogs", });
    internal_static_BlogMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BlogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlogMessage_descriptor,
        new String[] { "BlogId", "Content", "Longitude", "Latitude", "Address", "LikeCount", "CommentCount", "UserId", "IsLike", "Author", "AuthorPhoto", "CreateDt", "Images", });
    com.luckey.request_respose.ErrorMessageResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
